version: "3.3"

services:
  database:
    image: mysql:8.0
    container_name: engineering_database
    restart: always
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=engenharia
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=Biel.borel22
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build:
      context: .
    container_name: app
    env_file:
      - .env
    ports:
      - "80:3000"
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  db:
    driver: local
